### ISSUE TITLE
OpenXR error

### ISSUE THREAD

**Issue by CalM45** [mbucchia/Pimax-OpenXR#23]
FS2020 will not transition to VR and I sometimes get an OpenXR error, mostly I do not. Installing PimaxXR seemed to have broken my SteamVR (I probably broke it) and remains broken despite reinstalls, beta versions and registry edits. I had transitioned from OpenXR Toolkit 1.1.0. It seems to work 1 out of 50 times. However DCS works 100% of the time as it has nothing to do with STEAM (it seems). When I launch FS2020, my VR home environment is jittery and unstable.

Pimax Vision 8kx

[pimax-openxr 1.txt](https://github.com/mbucchia/Pimax-OpenXR/files/9542972/pimax-openxr.1.txt)

**Comment by mbucchia** [comment]
> PimaxXR seemed to have broken my SteamVR (I probably broke it) and remains broken despite reinstalls, beta versions and registry edits

PimaxXR doesn't touch anything SteamVR, so I believe your issue is elsewhere.

> sometimes get an OpenXR error, mostly I do not
> It seems to work 1 out of 50 times

I don't understand. You say "mostly I do not [have error]" then you say it works "1 out of 50". These two statements contradict each other. Does it work most of the time or not?

> I had transitioned from OpenXR Toolkit 1.1.0

1.1.0 is not supported with PimaxXR.

> When I launch FS2020, my VR home environment is jittery and unstable.

If you have not entered VR in the game, then this is 100%  not related to PimaxXR.


I'm sorry but your report is very very unclear, and there is nothing actionable for me at this time.

**Comment by mbucchia** [comment]
Maybe try disabling OpenXR Toolkit for now in case it's a bad setting causing the issue?

**Comment by CalM45** [comment]
"sometimes get an OpenXR error, mostly I do not
It seems to work 1 out of 50 times" 
- It does not work at all. The error message appears in the FS2020 sometimes but mostly there is no error message. Either way nothing happens.
----------------------
"sometimes get an OpenXR error, mostly I do not
It seems to work 1 out of 50 times"
- By this I meant as above, however on two occassions it randomly worked in VR after I changed the runtime in the regedit. I had tried several times after but could not replicate.
----------------------
"I had transitioned from OpenXR Toolkit 1.1.0" 
- I WAS using OpenXR 1.1.0 ToolKit with DCS for a few months. It works with the 8kx. I deleted it when I found PimaxXR
---------------------
As for PimaxXR and STEAM, doesn't PimaxXR replace the OpenVR runtime as per the 2 tickboxes at the top of the PimaxXR Control Centre? In that case it is affecting STEAM. 
---------------------

A few questions from your answers. 
1) Could Open Composite be conflicting with PimaxXR

2) Does the remove function on OpenXR supposed to purge every last trace of the ToolKit? I had reinstalled it to see if it was working and all my settings were intact.

3)Why does it run perfect with a non Steam game such as DCS?

**Comment by mbucchia** [comment]
> As for PimaxXR and STEAM, doesn't PimaxXR replace the OpenVR runtime as per the 2 tickboxes at the top of the PimaxXR Control Centre? In that case it is affecting STEAM.

This is just one registry key, you can set back to SteamVR. This is not affecting SteamVR per sei, it's only telling apps like MSFS or OpenComposite to use PimaxXR instead of SteamVR. If you select SteamVR from the Control Center app, it restores the 1 registry key back to what it was before.

You can also do it from SteamVR itself, by going to the Settings menu, Developer (need Advanced Settings to be shown) and click Set SteamVR as OpenXR runtime.

![image](https://user-images.githubusercontent.com/69611560/189544664-976288e8-20aa-4300-9917-abd6177d9ebb.png)

> Does the remove function on OpenXR supposed to purge every last trace of the ToolKit? I had reinstalled it to see if it was working and all my settings were intact.

If OpenXR Toolkit is not installed then those settings are not used anyway. So it doesn't matter that they are not purged.

> Why does it run perfect with a non Steam game such as DCS?

You are mixing up Steam (which is a content store) and SteamVR (which is a runtime environment for VR).

You can run DCS from inside of Steam just like you can run MSFS from outside of Steam. In your case it looks like you might have purchased MSFS from Steam rather than the MS Store but nonetheless you can run MSFS without Steam (I do it all the time), just create a Desktop shortcut that points to `steam://launch/1250410/VR`.  I would recommend you try that and see if it makes a difference.

**Comment by CalM45** [comment]
Ok thanks, I will look at creating that shortcut and will test with my other steam titles. 

Also, the reason I didn't change the runtime in steamvr is that if it blocks the HMD due to a critical error (which I forgot to mention), you do not get access the 'Steam VR settings' window and cannot change it. 

I will try all this tomorrow and will close the query shortly after. 
Thanks again
