### ISSUE TITLE
Bonelab knuckles positional/rotational offset. 

### ISSUE THREAD

**Issue by denis34343** [mbucchia/Pimax-OpenXR#31]
If controller Emulation is used(which is necessary if you want the grip to work) the controllers will have a weird rotational and positional offset. An rather easy fix would be to provide the option to set your controller offset manually. Another possible fix would be getting the knuckles Fingertracking to work for Bonelab. But I guess that's a problem on SLZs side.

**Comment by mbucchia** [comment]
Knuckles are working fine for me with that game. I use the rule of "pretend to hold a firearm and aim straight ahead with my eyes closed. Open my eyes, the aim ray is pointing exactly forward as expected".

Have you tried other games? Can you describe the offsets?

Providing the option to change offsets is way more complex than it looks because then people will ask to start having a better UI, and be able to do this per game, or have hotkeys to change the values, etc... it's an open door to an endless string of work.

Finger tracking isn't possible in bonelab because the game only accepts a single input for grip, it doesn't accepf individual fingers input.

**Comment by denis34343** [comment]
https://user-images.githubusercontent.com/73022874/194773582-a63c1574-5c9a-4b8e-98bf-e6e6458e41ad.mp4

This is the offset I'm talking about.
I have not tried other games but I will now.
Custom offsets don't need an UI. A simple config would be enough. And then people can share their configs.

**Comment by denis34343** [comment]
https://user-images.githubusercontent.com/73022874/194773950-5f24917e-1577-4ab7-8656-f2becfd3b051.mp4

In Phasmophobia there is no offset noticeable. Seems to be a Bonelab problem (again)

**Comment by mbucchia** [comment]
I did some digging into bonelab and I figured out why their support of Index controllers is unreliable.

I am working on a change now that should make it playable without the Oculus emulation and that will allow individual fingers sensing. Hopefully this will fix your issue!

**Comment by WulfOfOdin** [comment]
Dude, that would be freaking amazing if you could get the index controllers fully operational!!

**Comment by denis34343** [comment]
If you need bug testers etc.  please hmu

**Comment by denis34343** [comment]
Any News on this?

**Comment by mbucchia** [comment]
Index Controller finger sensing is added in 80e0f6e24673f7cad9c3335f6388f7963e629fba, with tunable (via registry) orientations for all poses in 158ef4eba12cd17a95650198af46618cbec3dc00 and 2d26ee1ffcda127d931b97418e181cb07c02ce41.
