### ISSUE TITLE
Image stutters when frame rates are between 1:2hz and 1:1hz.

### ISSUE THREAD

**Issue by DJSlane** [mbucchia/Pimax-OpenXR#44]
Image stutters when frame rates are between 1:2hz and 1:1hz. First noted by TommyVR https://discord.com/channels/933220354401398785/950124402337525840/1062066968561201182

Pitool 0.280
PimaxXR 0.3.0

Appears to Occur in all non-OpenXR games such as DCS, Subnautica, and Dirt Rally 2
It does not appear to occur in MSFS or Bonelab.

**Comment by ms-tech2010** [comment]
I have the same problem. Massive stuttering when the screen refresh are below setting in options. I tested any pitool version from 271 to  284. PimaxXR 0.30

**Comment by ms-tech2010** [comment]
I tested with PimaxXR runtime 0.32 the problem still existing.

**Comment by ms-tech2010** [comment]
I hope will be the little bit chance to resolve the problem because PimaxXR runtime in the ver 2.8 don't have THIS problem. Works good if refresh rate of game is below then Pitool setup [120/90/72Hz]. I'm not using any pitool fichers like Smart Smoothing or Hidden Area Mask. I checked PimaxXR runtime 3.0 - 3.2 in the Asseto Corsa; Asseto Corsa Competizione; AMS2; Project Cars 2.
I try to record video file and share you to see what is going on.
In the other case PimaxXR Runtime 2.8 is incompatible with OpenXR Toolkit in this games. When I try to run any game then I have a crash on start. 
Using: RTX 3090ti on 528.49 DCH display driver with Pimax Artistan 2.0 
Maybe it's the time to check any different standard gaming NV driver.

**Comment by ms-tech2010** [comment]
Tearing [120Hz : 90Hz in game] and no tearing mp4 videos [90Hz : 110Hz in game]. 
https://mega.nz/file/h14GwbqC#JDHV71DaubCm_EoMe_FXIKWDImgm2tmWdMHOdDw3mC8
https://mega.nz/file/4oARHTrS#UrJXWj_uTXo9izdo39bAdIdLP-O_5dutnsDGZ-7Cq9s

**Comment by mbucchia** [comment]
This is a useful observation, however 0.2.8 did a lot of things wrong for OpenXR apps.

0.3.0 and above are doing the proper implementation of OpenXR standard for frame management.

It's unfortunate that the proper way breaks with OpenComposite, but the project is called PimaxXR, not PimaxComposite. Between MSFS, Bonelab etc being broken, and fake OpenXR apps like AMS2, ACC etc being broken, my choice is quick :)

I will take a look at somehow allowing both 0.2.8 behavior and 0.3.0 behavior in the same version, but I already know doing this will break Smart Smoothing.

Unfortunately they're are many issues with the underlying Pimax software, and I need to choose to fix one scenario or the other. As mentioned above, solving the problem for fake OpenXR apps isn't my priority.

**Comment by mbucchia** [comment]
I've received feedback that PimaxXR 0.3.4 + Pimax Client 1.10 works fine with no stuttering under those conditions. Closing, please comment back here if that combination does not work for you.
