### ISSUE TITLE
Constant stuttering on latest PimaxXR now am not able to use PimaxXR 0.1.2

### ISSUE THREAD

**Issue by lv426hudson** [mbucchia/Pimax-OpenXR#53]
Hi, 

I have a periodic stutter which basically makes DCS unplayable as it happens almost all the time (even when playing offline) when using PimaxXR 0.3.2 and OXRTK 1.2.4 in DCS 2.8.3.37854.1 Open Beta. However I have had this issue in many versions of DCS and in all versions of PimaxXR, except 0.1.2 with OXRTK 1.1.0. 

With PimaxXR 0.1.2 these stutters were non existent, so I got around the issue by never upgrading PimaxXR. Unfortunately now PImaxXR 0.1.2 just causes DCS to crash when it boots, so I'm forced to use the latest PimaxXR which comes along with this stutter :-(

When doing the exact same instant action mission using SteamVR these spikes are not present and its smooth.

Between the stutters with PimaxXR I can see that the fps is quite a bit higher than when using SteamVR, but sadly the stutters just make it unplayable.

Any advice on how to resolve this would be much appreciated.

My Specs:
Windows 10
Intel i9 10900K
Gigabyte AORUS GeForce RTX 3090 XTREME WATERFORCE WB
Gigabyte Z490 AORUS ULTRA
M.2 Storage

[pimax-openxr.log](https://github.com/mbucchia/Pimax-OpenXR/files/11008213/pimax-openxr.log)
![335682716_759719235525881_4721225466582140134_n](https://user-images.githubusercontent.com/44461783/226099175-a57a6799-94aa-46c9-8384-412d8f13b506.jpg)

**Comment by mbucchia** [comment]
There is something about the way DCS uses OpenXR that does not work well with PimaxXR > 0.2.8. I'm aware of this issue, however I will likely not have a chance to work on that until May.

I am told that using OpenComposite rather than DCS native OpenXR mode still works, as long as you are not using DCS OpenBeta multi-threaded mode.
I am also told that people a found a combination of Turbo Mode and frame throttling that removes the issue (see my Discord). I've tested neither of these, since again, I am off this project at this time.

**Comment by weckermacher** [comment]
I seem to have the same issue. Glitch, stutter, wiggling, "2nd picture with big offset" caused by my head movements or objects in DCS moving. unusable.

Weirdly when I hit "Alt+Tab" to bring another App in the foreground the Problem is gone! Window out of focus and therefore unable to interact but when I look around I get no stutters or dragging glitching picture anymore. 

Constant 70+ FPS on the FPS counter.

System: All maxed out :) i9+4090+64gb ram+(...)

**Comment by mbucchia** [comment]
> Weirdly when I hit "Alt+Tab" to bring another App in the foreground the problem is gone

Do you have windows HAGS on? This issue happens to me when I have windows HAGS on and goes away if I turn it off.

**Comment by weckermacher** [comment]
> > Weirdly when I hit "Alt+Tab" to bring another App in the foreground the problem is gone
> 
> Do you have windows HAGS on? This issue happens to me when I have windows HAGS on and goes away if I turn it off.

Seems to only solve the problem partially. The stutters and the drag is 99% gone. But the frame drops and wiggling stays terrible. Wonder if it's tracking issues. Never mind. Thanks for your help anyways. And of course for what you have created. :)

**Comment by mbucchia** [comment]
Can you try PimaxXR 0.3.4 with Pimax Client 1.10? The combination of both is reported to have no performance issues?

**Comment by weckermacher** [comment]
I will try that. Thank you very much. I will let you know how it goes!Jan SundagMotion.Design.Artist.Filmkonzeption // Regie //Animation/Post // ***@***.*** 08.05.2023 um 08:39 schrieb Matthieu Bucchianeri ***@***.***>:﻿
Can you try PimaxXR 0.3.4 with Pimax Client 1.10? The combination of both is reported to have no performance issues?

**Comment by weckermacher** [comment]
Hello,first of all thanks again for what you are providing.I will try and give you a more detailed description of the problem I am seeing:I am on PimaxXR v0.3.4Pitool Version 1.0.1.277(I am downloading Pimax Client 1.10 from OpenMR now. I assume thats what you meant(?))I run a “--force_enable_VR --force_OpenXR” DCS openbeta multithreaded shortcut from desktop.DCS openbeta 2.8.3.38090Weird issue:Soon as I get into the DCS Main Menue my vision slowly starts “wobbling”. Within 5 sec it gets really bad so that I have to close my eyes not to get sick. If I dont move the mouse and wait long enough ( maybe 20 sec) it settles. Then I can see that my head movement is crazy “amplified”. The tiniest movement becomes a bigger shake. I can see the micromovements my head makes when I concentrate to keep it 100% still. I can see micromovents caused by my very calm heartbeat for example. Looks like when I then move the mouse i get back to the heavy shakes from the beginning. Weird enough when I then start any mission in a plane it’s completely gone. Everything runs fine! Also in mission editor. It seems that loading into an entirely other part of the application fixes it. Coming back to the Menue the issue is back right away.If you are intersted in this problem I will be happy to provide more info and whatever kind of data you need.Thanks againBestJanJan SundagMotion.Design.Artist.Filmkonzeption // Regie //Animation/Post // ***@***.*** 08.05.2023 um 08:39 schrieb Matthieu Bucchianeri ***@***.***>:﻿
Can you try PimaxXR 0.3.4 with Pimax Client 1.10? The combination of both is reported to have no performance issues?

**Comment by weckermacher** [comment]
Sry to bother you further but this might also really help me:Where does PimaxXR take the “floor hight” from and what is it? How is this set and can it be adjusted? Its about 25cm above my actual head hight when I sit in the seat.Might this be the reason my vision is “rolling out of the cockpit” in DCS?Thanks again.JanJan SundagMotion.Design.Artist.Filmkonzeption // Regie //Animation/Post // ***@***.*** 22.05.2023 um 21:27 schrieb Jan Sundag ***@***.***>:﻿Hello,first of all thanks again for what you are providing.I will try and give you a more detailed description of the problem I am seeing:I am on PimaxXR v0.3.4Pitool Version 1.0.1.277(I am downloading Pimax Client 1.10 from OpenMR now. I assume thats what you meant(?))I run a “--force_enable_VR --force_OpenXR” DCS openbeta multithreaded shortcut from desktop.DCS openbeta 2.8.3.38090Weird issue:Soon as I get into the DCS Main Menue my vision slowly starts “wobbling”. Within 5 sec it gets really bad so that I have to close my eyes not to get sick. If I dont move the mouse and wait long enough ( maybe 20 sec) it settles. Then I can see that my head movement is crazy “amplified”. The tiniest movement becomes a bigger shake. I can see the micromovements my head makes when I concentrate to keep it 100% still. I can see micromovents caused by my very calm heartbeat for example. Looks like when I then move the mouse i get back to the heavy shakes from the beginning. Weird enough when I then start any mission in a plane it’s completely gone. Everything runs fine! Also in mission editor. It seems that loading into an entirely other part of the application fixes it. Coming back to the Menue the issue is back right away.If you are intersted in this problem I will be happy to provide more info and whatever kind of data you need.Thanks againBestJanJan SundagMotion.Design.Artist.Filmkonzeption // Regie //Animation/Post // ***@***.*** 08.05.2023 um 08:39 schrieb Matthieu Bucchianeri ***@***.***>:﻿
Can you try PimaxXR 0.3.4 with Pimax Client 1.10? The combination of both is reported to have no performance issues?

**Comment by mbucchia** [comment]
Please try the new release 0.4.0.
